Repository wultra/powerauth-server, pull requests merged in 2024-10, with the labels that each got.

#1686 Fix #662: Document activation OTP mode behaviors better
  docs/WebServices-Methods.md
Labels: docs

#1685 Fix #1684: Update Client and Admin Console
  powerauth-admin/src/main/java/io/getlime/security/app/admin/controller/ApplicationController.java
  powerauth-admin/src/main/webapp/WEB-INF/jsp/applicationDetail.jsp
  powerauth-admin/src/main/webapp/WEB-INF/jsp/callbackCreate.jsp
  powerauth-admin/src/main/webapp/WEB-INF/jsp/callbackUpdate.jsp
  powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/PowerAuthClient.java
  powerauth-rest-client-spring/src/main/java/com/wultra/security/powerauth/rest/client/PowerAuthRestClient.java
Labels: release

#1736 Fix #1735: Allow retrieving temporary keys for blocked activations
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/TemporaryKeyBehavior.java
Labels: enhancement

#1742 Add deprecations for client methods without all crypto 3.3 parameters
  docs/PowerAuth-Server-1.9.0.md
  powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/PowerAuthClient.java
Labels: enhancement

#1746 Fix #1717: Cover temporary keys functionality with unit tests
  powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java
  powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/TemporaryKeyBehaviourTest.java
Labels: enhancement

#1759 Fix #1755: Backport fix of #1753 to 1.8.x branch
  pom.xml
  powerauth-admin/pom.xml
  powerauth-client-model/pom.xml
  powerauth-fido2-model/pom.xml
  powerauth-fido2/pom.xml
  powerauth-java-server/pom.xml
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehavior.java
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthAssertionProvider.java
  powerauth-java-server/src/test/java/com/wultra/powerauth/fido2/Fido2AuthenticatorTest.java
  powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehaviorTest.java
  powerauth-rest-client-spring/pom.xml
Labels: hotfix

#1760 Fix #1756: Backport fix of #1753 to 1.7.x branch
  pom.xml
  powerauth-admin/pom.xml
  powerauth-client-model/pom.xml
  powerauth-fido2/pom.xml
  powerauth-java-server/pom.xml
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehavior.java
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthAssertionProvider.java
  powerauth-java-server/src/test/java/com/wultra/powerauth/fido2/Fido2AuthenticatorTest.java
  powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehaviorTest.java
  powerauth-rest-client-spring/pom.xml
Labels: hotfix

#1761 Fix #1757: Backport fix of #1753 to 1.6.x branch
  pom.xml
  powerauth-admin/pom.xml
  powerauth-client-model/pom.xml
  powerauth-java-server/pom.xml
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehavior.java
  powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehaviorTest.java
  powerauth-rest-client-spring/pom.xml
Labels: hotfix
