Repository wultra/powerauth-server, pull requests merged in 2024-03, with the labels that each got.

#1369 Fix #1368: Modify datatype of pa_activation.extras
  docs/db/changelog/changesets/powerauth-java-server/1.7.x/20240115-add-columns-fido2.xml
Labels: bug, release

#1387 Fix #1386: FIDO2: Parameter externalId from AssertionChallengeRequest is ignored
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthAssertionProvider.java
Labels: bug

#1389 Fix #1388: FIDO2: Reversed order of parameters in findByCredentialId
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/AssertionService.java
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthAuthenticatorProvider.java
Labels: bug

#1395 Fix #1391: FIDO2: Names refactoring
  powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/entity/fido2/AuthenticatorDetail.java
  powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/response/fido2/RegistrationResponse.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/RegistrationConverter.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/entity/AuthenticatorDetail.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/response/RegistrationResponse.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/AssertionService.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/RegistrationService.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/provider/CryptographyService.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/provider/RegistrationProvider.java
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/ActivationRepository.java
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthAuthenticatorProvider.java
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthCryptographyService.java
  powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthRegistrationProvider.java
Labels: enhancement

#1406 Fix #1402: FIDO2: Handle nullability in REST API requests for initialized collections
  powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/request/fido2/AssertionVerificationRequest.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/entity/AuthenticatorParameters.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/request/AssertionChallengeRequest.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/request/AssertionVerificationRequest.java
Labels: enhancement

#1405 Fix #1404: FIDO2: REST API request / response class cleanup
  powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/entity/fido2/AuthenticatorParameters.java
  powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/request/fido2/AssertionVerificationRequest.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/controller/AssertionController.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/RegistrationConverter.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/entity/AuthenticatorParameters.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/request/AssertionVerificationRequest.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/response/AssertionChallengeResponse.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/response/AssertionVerificationResponse.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/response/RegistrationChallengeResponse.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/AssertionService.java
  powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/RegistrationService.java
  powerauth-java-server/src/test/java/com/wultra/powerauth/fido2/Fido2AuthenticatorTest.java
  powerauth-rest-client-spring/src/main/java/com/wultra/security/powerauth/rest/client/PowerAuthFido2RestClient.java
Labels: enhancement
